version: '3.8'

services:

  purchases-eventstore:
     
     container_name: "purchases-eventstore"
     
     image: eventstore/eventstore:latest

     environment:
         - EVENTSTORE_CLUSTER_SIZE=1
         - EVENTSTORE_RUN_PROJECTIONS=All
         - EVENTSTORE_START_STANDARD_PROJECTIONS=true
         - EVENTSTORE_EXT_TCP_PORT=1113
         - EVENTSTORE_HTTP_PORT=2113
         - EVENTSTORE_INSECURE=true
         - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
         - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      
     ports:
         - 6113:1113
         - 7113:2113

     volumes:
         - type: volume
           source: purchases-eventstore-data
           target: /var/lib/purchases-eventstore
         - type: volume
           source: purchases-eventstore-logs
           target: /var/log/purchases-eventstore

  purchases-mongodb:
      image: mongo
      ports:
          - 27017:27017

      volumes:
         - type: volume
           source: purchases-mongodb-data
           target: /var/lib/purchases-mongodb
  
  rabbitmq:
      image: rabbitmq:3.8-management-alpine
      ports:
          - 5672:5672
          - 15672:15672

  purchases-rest:
      image: ${REGISTRY:-brewup}/purchases.rest:${PLATFORM:-linux}-${TAG:-latest}
      build:
        context: .
        dockerfile: Purchases/Dockerfile
      ports:
          - 5000:80
          - 5001:443
      depends_on:
        - purchases-eventstore
        - purchases-mongodb
        - rabbitmq

volumes:
  purchases-eventstore-data:
  purchases-eventstore-logs:
  purchases-mongodb-data:
